Note that to use Greek letters simply type \alpha then press tab

In [1]:
α=0.5

0.5

In [2]:
typeof(α)

Float64

In [6]:
using Distributions

In [7]:
struct AR1{T <: Real}
    a::T
    b::T
    σ::T
    ϕ::Distribution
end

In [8]:
m = AR1(0.9, 1.0, 1.0, Beta(5, 5))

AR1{Float64}(0.9, 1.0, 1.0, Distributions.Beta{Float64}(α=5.0, β=5.0))

In [13]:
function simulate(m::AR1, n::Integer, x0::Real) 
    
    X = Array{Float64}(n)
    X[1] = x0
    
    for t in 1:(n-1)
        X[t+1] = m.a * X[t] + m.b + m.σ * rand(m.ϕ)
    end
    
    return X
end

simulate (generic function with 1 method)

In [14]:
simulate(m,100,0)

100-element Array{Float64,1}:
  0.0    
  1.62435
  3.04075
  3.97345
  4.92105
  5.96121
  6.73686
  7.35233
  8.17899
  8.8037 
  9.25347
  9.64752
 10.3036 
  ⋮      
 14.8086 
 15.0576 
 15.1305 
 14.8641 
 14.9064 
 14.9477 
 14.8391 
 14.7153 
 14.7504 
 14.7734 
 14.6089 
 14.6075 

In [2]:
using QuantEcon

In [3]:
P = rouwenhorst(3, 0.96566, sqrt(0.01695/(1-0.96566^2)), 0)

Discrete Markov Chain
stochastic matrix of type Array{Float64,2}:
[0.965955 0.0337504 0.000294809; 0.0168752 0.96625 0.0168752; 0.000294809 0.0337504 0.965955]

In [9]:
m.a

0.9

In [10]:
P.state_values

-2.727665798036792:2.727665798036792:2.727665798036792

In [11]:
P.p

3×3 Array{Float64,2}:
 0.965955     0.0337504  0.000294809
 0.0168752    0.96625    0.0168752  
 0.000294809  0.0337504  0.965955   

In [22]:
typeof(exp.(P.state_values))

Array{Float64,1}

In [18]:
dim(P.state_values)

LoadError: MethodError: no method matching dim(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}})
Closest candidates are:
  dim(::PDMats.PDMat) at /Users/Anirudh/.julia/v0.6/PDMats/src/pdmat.jl:26
  dim(::PDMats.PDSparseMat) at /Users/Anirudh/.julia/v0.6/PDMats/src/pdsparsemat.jl:24
  dim(::PDMats.PDiagMat) at /Users/Anirudh/.julia/v0.6/PDMats/src/pdiagmat.jl:23
  ...

In [20]:
typeof(P.state_values)

StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}

In [23]:
meshgrid(x,y) = (repmat(x',length(y),1),repmat(y,1,length(x)));

In [24]:
x = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [25]:
y= [4,5,6]

3-element Array{Int64,1}:
 4
 5
 6

In [26]:
meshgrid(x,y)

([1 2 3; 1 2 3; 1 2 3], [4 4 4; 5 5 5; 6 6 6])

In [30]:
x.^2

3-element Array{Int64,1}:
 1
 4
 9

In [39]:
x = -7:7 
y = sin.(x)
xf = -7:0.1:7

-7.0:0.1:7.0

In [32]:
li = LinInterp(x, y)

QuantEcon.LinInterp{Array{Float64,1},UnitRange{Int64}}(-7:7, [-0.656987, 0.279415, 0.958924, 0.756802, -0.14112, -0.909297, -0.841471, 0.0, 0.841471, 0.909297, 0.14112, -0.756802, -0.958924, -0.279415, 0.656987], 15, 1)

In [33]:
y_linear_qe = li.(xf)

141-element Array{Float64,1}:
 -0.656987  
 -0.563346  
 -0.469706  
 -0.376066  
 -0.282426  
 -0.188786  
 -0.0951453 
 -0.00150513
  0.0921351 
  0.185775  
  0.279415  
  0.347366  
  0.415317  
  ⋮         
 -0.347366  
 -0.279415  
 -0.185775  
 -0.0921351 
  0.00150513
  0.0951453 
  0.188786  
  0.282426  
  0.376066  
  0.469706  
  0.563346  
  0.656987  

In [52]:
using Interpolations

In [41]:
itp_const = scale(interpolate(y, BSpline(Constant()), OnGrid()), x)

LoadError: MethodError: no method matching scale(::Interpolations.BSplineInterpolation{Float64,1,Array{Float64,1},Interpolations.BSpline{Interpolations.Constant},Interpolations.OnGrid,0}, ::UnitRange{Int64})

In [42]:
A = rand(20)

20-element Array{Float64,1}:
 0.657282 
 0.41764  
 0.966742 
 0.433983 
 0.914784 
 0.268112 
 0.766252 
 0.748504 
 0.495582 
 0.971046 
 0.181614 
 0.515275 
 0.0396085
 0.387376 
 0.911528 
 0.310442 
 0.641784 
 0.328174 
 0.584493 
 0.774057 

In [43]:
A_x = collect(1.0:2.0:40.0)
knots = (A_x,)

([1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0, 19.0, 21.0, 23.0, 25.0, 27.0, 29.0, 31.0, 33.0, 35.0, 37.0, 39.0],)

In [46]:
typeof(knots)

Tuple{Array{Float64,1}}

In [49]:
itp = interpolate(knots, A, Gridded(Cubic()))

LoadError: MethodError: no method matching Interpolations.Cubic()
Closest candidates are:
  Interpolations.Cubic(::BC<:Interpolations.Flag) where BC<:Interpolations.Flag at /Users/Anirudh/.julia/v0.6/Interpolations/src/b-splines/cubic.jl:2

In [57]:
using Interpolations
A = rand(20, 10)
xs = 1:20
ys = 1:10
f = CubicSplineInterpolation((xs,ys), A)

LoadError: UndefVarError: CubicSplineInterpolation not defined

In [1]:
using QuantEcon

In [2]:
P = [0.4 0.6; 0.2 0.8]

2×2 Array{Float64,2}:
 0.4  0.6
 0.2  0.8

In [3]:
nrow = size(P)[1]

2

In [9]:
P_dist = [DiscreteRV(vec(P[i,:])) for i in 1:nrow]

2-element Array{QuantEcon.DiscreteRV{Array{Float64,1},Array{Float64,1}},1}:
 QuantEcon.DiscreteRV{Array{Float64,1},Array{Float64,1}}([0.4, 0.6], [0.4, 1.0])
 QuantEcon.DiscreteRV{Array{Float64,1},Array{Float64,1}}([0.2, 0.8], [0.2, 1.0])

In [10]:
function mc_sample_path(P; init=1, sample_size=1000)
    X = Array{Int64}(sample_size) # allocate memory
    X[1] = init
    # === convert each row of P into a distribution === #
    n = size(P)[1]
    P_dist = [DiscreteRV(vec(P[i,:])) for i in 1:n]

    # === generate the sample path === #
    for t in 1:(sample_size - 1)
        X[t+1] = rand(P_dist[X[t]])
    end
    return X
end

mc_sample_path (generic function with 1 method)

In [11]:
X = mc_sample_path(P, sample_size=10)

10-element Array{Int64,1}:
 1
 2
 2
 2
 1
 2
 1
 1
 2
 2

In [12]:
rand(P_dist[1])

2

In [13]:
Z = zeros(length(X));

In [14]:
for i in 1:length(Z)
    if X[i]==1
        Z[i]=2.3
    elseif X[i]==2
        Z[i]=3.2
        else Z[i]=4.6
    end
end

In [15]:
Z

10-element Array{Float64,1}:
 2.3
 3.2
 3.2
 3.2
 2.3
 3.2
 2.3
 2.3
 3.2
 3.2