## Q1(d) Cechetti, Lam and Mark - Distorted Beliefs

In [13]:
function cechettilam(gamma,beta) 
    
    # States
    s1 = 1.02252;
    s2 = 1-(6.785/100);

    # Lambda matrix
    Lambda = [s1^(1-gamma) 0; 0 s2^(1-gamma)];

    #Lambda column vector
    lambdavec = [s1, s2];

    # Vector and matrix of ones
    i=ones(2);
    I=eye(2);

    # Distorted Transition matrix
    p=0.6
    q=0.9
    P = [p 1-p; 1-q q];
    
    # True Transition matrix
    Pi = [0.987 1-0.987; 1-0.516 0.516]

    # Ergodic distribution across states
    Pi = Pi^1000;
    Pivec = Pi[1,:];
    
    # Risk free rate vector
    Rinv = beta*P*(lambdavec.^-gamma)
    R = Rinv.^(-1)
    #R = [1/Rinv[1] 1/Rinv[2]]

    #Unconditional (average) risk free rate
    Rbar = dot(Pivec,R)

    #Price/dividend ratios
    w=beta*(inv(I-beta*P*Lambda))*P*Lambda*i

    # Expected equity returns
    ERS = P*((lambdavec).*(1+w)).*[1/w[1] 1/w[2]]'

    # Unconditional (average) equity return
    RSbar = dot(Pivec,ERS)
    
    # Equity premium, per cent
    ep = (RSbar - Rbar)*100
    
    # RESULTS VECTOR
    ANS = [gamma, Rbar, RSbar, ep]
    
    return ANS
end;

#### Beta = 0.99

In [14]:
Results=hcat(["gamma", "Rf", "Re", "Re-Rf"],cechettilam(2,0.99),cechettilam(4,0.99),cechettilam(6,0.99),cechettilam(10,0.99))

4×5 Array{Any,2}:
 "gamma"   2.0        4.0        6.0        10.0     
 "Rf"      0.974491   0.932523   0.885016    0.777758
 "Re"      0.974368   0.913302   0.82337     0.552149
 "Re-Rf"  -0.012323  -1.9221    -6.16464   -22.5609  

#### Beta = 0.97

In [21]:
Results=hcat(["gamma", "Rf", "Re", "Re-Rf"],cechettilam(2,0.97),cechettilam(4,0.97),cechettilam(6,0.97),cechettilam(10,0.97))

4×5 Array{Any,2}:
 "gamma"  2.0          4.0        6.0        10.0     
 "Rf"     0.994584     0.95175    0.903264    0.793795
 "Re"     0.994627     0.933317   0.843737    0.576008
 "Re-Rf"  0.00437946  -1.84334   -5.95275   -21.7786  

### Cogley and Sargent version

In [16]:
function cogleysargent(gamma,beta,p,q) 
    
    # States
    s1 = 1.02252;
    s2 = 1-(6.785/100);

    # Lambda matrix
    Lambda = [s1^(1-gamma) 0; 0 s2^(1-gamma)];

    #Lambda column vector
    lambdavec = [s1, s2];

    # Vector and matrix of ones
    i=ones(2);
    I=eye(2);

    # Distorted Transition matrix
    P = [p 1-p; 1-q q];
    
    # True Transition matrix
    Pi = [0.987 1-0.987; 1-0.516 0.516]

    # Ergodic distribution across states
    Pi = Pi^1000;
    Pivec = Pi[1,:];
    
    # Risk free rate vector
    Rinv = beta*P*(lambdavec.^-gamma)
    R = Rinv.^(-1)
    #R = [1/Rinv[1] 1/Rinv[2]]

    #Unconditional (average) risk free rate
    Rbar = dot(Pivec,R)

    #Price/dividend ratios
    w=beta*(inv(I-beta*P*Lambda))*P*Lambda*i

    # Expected equity returns
    ERS = P*((lambdavec).*(1+w)).*[1/w[1] 1/w[2]]'

    # Unconditional (average) equity return
    RSbar = dot(Pivec,ERS)
    
    # Equity premium, per cent
    ep = (RSbar - Rbar)*100
    
    # RESULTS VECTOR
    ANS = [gamma, Rbar, RSbar, ep]
    
    return ANS
end;

#### Beta = 0.99

In [22]:
Results=hcat(["gamma", "Rf", "Re", "Re-Rf"],cogleysargent(2,0.99,0.915,0.805),cogleysargent(4,0.99,0.915,0.805),cogleysargent(6,0.99,0.915,0.805),cogleysargent(10,0.99,0.915,0.805))

4×5 Array{Any,2}:
 "gamma"   2.0        4.0        6.0       10.0    
 "Rf"      1.03475    1.05712    1.07648    1.10304
 "Re"      1.03198    1.0113     0.511232   1.50178
 "Re-Rf"  -0.277731  -4.5822   -56.5251    39.8737 

#### Beta = 0.97

In [23]:
Results=hcat(["gamma", "Rf", "Re", "Re-Rf"],cogleysargent(2,0.97,0.915,0.805),cogleysargent(4,0.97,0.915,0.805),cogleysargent(6,0.97,0.915,0.805),cogleysargent(10,0.97,0.915,0.805))

4×5 Array{Any,2}:
 "gamma"   2.0        4.0        6.0      10.0    
 "Rf"      1.05609    1.07891    1.09868   1.12579
 "Re"      1.05359    1.03839    0.73554   1.57699
 "Re-Rf"  -0.249625  -4.05223  -36.3139   45.1199 